### ISSUE TITLE
Cannot Access Live Website

### ISSUE THREAD

**Issue by JunyaoC** [tanchonglim/web-programming#1]
Hi Chong Lim! With regrets, I could not access minorsales.xyz! Would like to take a look of your great work!

**Comment by tanchonglim** [comment]
Unfortunately, I had no longer access to that domain. You may host it on your local machine.

**Comment by JunyaoC** [comment]
Hey there, just suggesting, since i have some domains laying around, may i take the initiative to host it on the internet?
